### ISSUE TITLE
NOT an issue!

### ISSUE THREAD

**Issue by ritiksoni00** [gbdlin/django-admin-sidebar#1]
where to add that 3rd point.??

**Comment by ritiksoni00** [comment]
@gbdlin can we fully customize the sidebar_menu?

**Comment by gbdlin** [comment]
This project is not supported and it is not compatible with any Django version out of the box. Please use https://github.com/gbdlin/django-admin-toolbox instead (but even the 2nd one is not guaranteed to work with recent versions of Django.

Currently I'm not supporting any of the projects and I will never support this one (I may pick up again the one linked above in future, but no guarantee). If you want to use any of them, you're unfortunately on your own.
